description: |
  Select a browser based variant executor.

parameters:
  tag:
    type: string
    default: "stable-browser"
    description: >
      Pick a specific cimg/base browser image version tag (or whatever your ):
      https://hub.docker.com/r/cimg/python
  image-name:
    type: string
    default: "base"
    description: >
      Pick a specific convinence-image
      https://hub.docker.com/r/cimg

docker:
  - image: cimg/<<parameters.image-name>>:<<parameters.tag>>
